### ISSUE TITLE
eosiodetroit block producer shown in wrong location on the map

### ISSUE THREAD

**Issue by robrigo** [cypherglassdotcom/glass#7]
Hello! Thanks for the useful tool. I wanted to point out an inaccuracy with our BP in the map:

https://glass.cypherglass.com/bp/eosiodetroit

The map is rendering our nodes in China:

![screen shot 2018-07-24 at 12 43 24 pm](https://user-images.githubusercontent.com/590263/43153432-4caf6734-8f3f-11e8-9c93-c5c4a21e3ce2.png)

We published 840 for our ISO 3166-1 numeric country code (USA) when we called regproducer: https://eospark.com/MainNet/tx/554e4360cff694cb48f2047cdc2957c95c40674c3cc6e0da10b499dec6a3e5ab

Our BP.json also includes lat and long coordinates in Columbus, Ohio under each node:

http://eosdetroit.io/bp.json

**Comment by postfunk** [comment]
Hi Robert.  Thanks for checking out Glass.  Your longitude is missing a minus sign in your bp.json file.  It should be negative.

"location": {
"name": "Detroit",
"country": "US",
"latitude": 42.3314,
**_"longitude": 83.0458_**

**Comment by robrigo** [comment]
Great catch, thanks. :)
